### ISSUE TITLE
react项目中引用之后webpack打包发布线上报错，请问怎么解决

### ISSUE THREAD

**Issue by zoomwang** [aisuda/amis-editor-demo#120]
Uncaught TypeError: (0 , i.setSchemaTpl) is not a function
    at Object.4870 (app.js:145041:36)
    at o (app.js:147302:24)
    at app.js:147342:22
    at app.js:147449:11
    at Object.<anonymous> (app.js:147455:7)
    at o (app.js:18:21)
    at Module.<anonymous> (app.js:215610:23)
    at o (app.js:18:21)
    at HTMLScriptElement.callback (app.js:149251:40)

**Comment by zoomwang** [comment]
Uncaught TypeError: (0 , i.setSchemaTpl) is not a function
    at Object.4870 (app.js:145041:36)
    at o (app.js:147302:24)
    at app.js:147342:22
    at app.js:147449:11
    at Object.<anonymous> (app.js:147455:7)
    at o (app.js:18:21)
    at Module.<anonymous> (app.js:215610:23)
    at o (app.js:18:21)
    at HTMLScriptElement.callback (app.js:149251:40)

**Comment by mrsmallyi** [comment]
同问，我也有这个问题 @nwind @zoomwang

**Comment by mrsmallyi** [comment]
![image](https://user-images.githubusercontent.com/17785263/169797027-4586eee2-930c-4f88-aac6-8eb0b56a8edd.png)
@nwind

**Comment by wibetter** [comment]
请将amis和amis-editor相关模块升级到最新版本。
